spring:
  application:
    name: room-service		
  data:
    mongodb:
      uri: mongodb://localhost:27017/room		
logging:
  level:
    root: INFO
    com.piseth.java.school: DEBUG

#springdoc:
#   api-docs:
#       path: localhosh:8065
#   swagger-ui:
#       path: /swagger-ui/index.html
#       operationsSorter: method
#       disable-swagger-default-url: false

server:
  port: 8065